// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaYuUjQoSmxY4WvO4yeEwCWQ5OzTVFC8E',
    appId: '1:601984325673:web:6bb8e0d23fb2e6660de438',
    messagingSenderId: '601984325673',
    projectId: 'crud-eabba',
    authDomain: 'crud-eabba.firebaseapp.com',
    storageBucket: 'crud-eabba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALz90N_mwRluT7iftTO832cK-5W_Flzd0',
    appId: '1:601984325673:android:c4ef687d28c3f8260de438',
    messagingSenderId: '601984325673',
    projectId: 'crud-eabba',
    storageBucket: 'crud-eabba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoq3KzvFJ4mOA30CniETlTM1eN3UyoeTk',
    appId: '1:601984325673:ios:735e86acd3bfacfb0de438',
    messagingSenderId: '601984325673',
    projectId: 'crud-eabba',
    storageBucket: 'crud-eabba.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoq3KzvFJ4mOA30CniETlTM1eN3UyoeTk',
    appId: '1:601984325673:ios:735e86acd3bfacfb0de438',
    messagingSenderId: '601984325673',
    projectId: 'crud-eabba',
    storageBucket: 'crud-eabba.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaYuUjQoSmxY4WvO4yeEwCWQ5OzTVFC8E',
    appId: '1:601984325673:web:dcf205645f2d94060de438',
    messagingSenderId: '601984325673',
    projectId: 'crud-eabba',
    authDomain: 'crud-eabba.firebaseapp.com',
    storageBucket: 'crud-eabba.appspot.com',
  );
}
